### ISSUE TITLE
Non-bootable output image

### ISSUE THREAD

**Issue by simonowen** [stefandrissen/samdos#1]
While technically matching the original source code, the assembled output file includes the hidden 9-byte disk header, which means the output can't be used as-is by other projects. I'd guess that the original version included the header so it could be written directly to a disk from cyl 4 sector 1 using only raw sector writes, without the need for a fully working DOS.

With the source now preserved in the history, would it be better to add an extra commit to give the tradtiional 10000 byte output?

**Comment by stefandrissen** [comment]
Moved raw mode inside 'include-header' define and updated the reference file.
